services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: wornux/urlshortener:latest
    container_name: urlshortener_app
    environment:
      PORT: ${APP_PORT:-7000}
      PORT_GRPC: ${APP_PORT_GRPC:-9090}
      MONGODB_URL: ${MONGODB_URL}
    ports:
      - "${APP_PORT:-7000}:${APP_PORT:-7000}"
      - "${APP_PORT_GRPC:-9090}:${APP_PORT_GRPC:-9090}"
    volumes:
      - app-logs:/app/logs

volumes:
  app-logs:
